import PDFDocument from 'pdfkit';

export async function generateReportPDF(title: string, type: string, content: string): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 });
    const chunks: Buffer[] = [];

    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', (err) => reject(err));

    // Header
    doc.fontSize(25).text('TenderIQ AI Report', { align: 'center' });
    doc.moveDown();
    
    doc.fontSize(18).text(title, { align: 'center' });
    doc.fontSize(14).text(`Type: ${type.replace(/_/g, ' ')}`, { align: 'center' });
    doc.moveDown();

    // Line
    doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
    doc.moveDown();

    // Content
    doc.fontSize(12).text(content, {
      align: 'justify',
      lineGap: 5,
    });

    // Footer
    const pageCount = (doc as any).bufferedPageRange().count;
    for (let i = 0; i < pageCount; i++) {
      doc.switchToPage(i);
      doc.fontSize(10).text(
        `Generated by TenderIQ AI - Page ${i + 1}`,
        50,
        doc.page.height - 50,
        { align: 'center' }
      );
    }

    doc.end();
  });
}
